export const REQUEST_INITIAL_SUCCESS = "REQUEST_INITIAL_SUCCESS";
export const REQUEST_INITIAL_FAILURE = "REQUEST_INITIAL_FAILURE";
export const REQUEST_CURRENCY_SUCCESS = "REQUEST_CURRENCY_SUCCESS";
export const REQUEST_CURRENCY_FAILURE = "REQUEST_CURRENCY_FAILURE";
export const UPDATE_BASE_AMOUNT = "UPDATE_BASE_AMOUNT";
