export const REQUEST_CREATE_SESSION_SUCCESS = "REQUEST_CREATE_SESSION_SUCCESS";
export const REQUEST_CREATE_SESSION_FAILURE = "REQUEST_CREATE_SESSION_FAILURE";
export const APP_CODE = "94dB68k5R3r7bL5q1";