export const REQUEST_CREATE_SESSION_SUCCESS = "REQUEST_CREATE_SESSION_SUCCESS";
export const REQUEST_CREATE_SESSION_FAILURE = "REQUEST_CREATE_SESSION_FAILURE";
export const REQUEST_INITIALIZATION_DATA_SUCCESS = "REQUEST_INITIALIZATION_DATA_SUCCESS";
export const REQUEST_INITIALIZATION_DATA_FAILURE = "REQUEST_INITIALIZATION_DATA_FAILURE";
export const REQUEST_NEW_CURRENCY_SUCCESS = "REQUEST_NEW_CURRENCY_SUCCESS";
export const REQUEST_NEW_CURRENCY_FAILURE = "REQUEST_NEW_CURRENCY_FAILURE";
export const IS_UPDATING = "IS_UPDATING";
export const APP_CODE = "94dB68k5R3r7bL5q1";